<?php

/**
 * @file
 * Contains kino_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kino_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kino_entity module.
    case 'help.page.kino_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function kino_entity_theme() {
  $theme = [];
  $theme['kino_entity'] = [
    'render element' => 'elements',
    'file' => 'kino_entity.page.inc',
    'template' => 'kino_entity',
  ];
  $theme['kino_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'kino_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function kino_entity_theme_suggestions_kino_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#kino_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'kino_entity__' . $sanitized_view_mode;
  $suggestions[] = 'kino_entity__' . $entity->bundle();
  $suggestions[] = 'kino_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'kino_entity__' . $entity->id();
  $suggestions[] = 'kino_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
