<?php

/**
 * @file
 * Contains kino_status.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kino_status_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kino_status module.
    case 'help.page.kino_status':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function kino_status_theme() {
  $theme = [];
  $theme['status_entity'] = [
    'render element' => 'elements',
    'file' => 'status_entity.page.inc',
    'template' => 'status_entity',
  ];
  $theme['status_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'status_entity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function kino_status_theme_suggestions_status_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#status_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'status_entity__' . $sanitized_view_mode;
  $suggestions[] = 'status_entity__' . $entity->bundle();
  $suggestions[] = 'status_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'status_entity__' . $entity->id();
  $suggestions[] = 'status_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
